<?php

namespace App\Services;

class CampaignPresetService
{
    /**
     * Get all 20 corporate presets for Suitable B2B email campaigns
     */
    public static function all(): array
    {
        return [
            [
                'id' => 'clasica',
                'name' => 'Clásica B2B Institucional',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '🏛️ Más Popular',
                'color' => '#1E8888',
                'icon' => '🏛️',
                'description' => 'Estructura institucional completa con Hero Banner de bienvenida, 3 columnas de pilares de fábrica nacional, garantía y botón CTA corporativo.',
                'subject' => '[Convenio Clínico] Uniformes médicos con 6 meses de garantía directa de fábrica y servicio de tallaje',
                'preheader' => 'Somos fabricantes chilenos de uniformes clínicos antifluidos. Servicio exclusivo de tallaje en su clínica y 6 meses de garantía.',
                'hero_title' => 'Distinción y Confort para su Equipo Médico',
                'hero_desc' => 'En Suitable confeccionamos uniformes clínicos de alto rendimiento con telas antifluidos de última generación y respaldo integral de fábrica. Llevamos muestras en vivo a su clínica para que su equipo pruebe tallas antes de comprar.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Fabricación 100% Chilena',
                'pilar1_desc' => 'Confección directa en nuestros talleres, sin intermediarios ni demoras de importación.',
                'pilar2_title' => 'Telas Flex Antifluidos',
                'pilar2_desc' => 'Tecnología stretch cuatridireccional que repele líquidos y asegura movilidad total en turnos exigentes.',
                'pilar3_title' => 'Garantía y Tallaje en Terreno',
                'pilar3_desc' => 'Llevamos percheros móviles con todas las tallas directo a su clínica y damos 6 meses de garantía de costura.',
                'cta_text' => 'Solicitar Catálogo Institucional →',
                'cta_url' => 'https://suitable.cl/catalogo-corporativo',
                'layout_type' => 'pillars'
            ],
            [
                'id' => 'tallaje',
                'name' => 'Tallaje en Terreno 1-2-3',
                'category' => 'Tallaje & Servicio',
                'category_slug' => 'tallaje',
                'badge' => '📏 Cero Errores',
                'color' => '#0F766E',
                'icon' => '📏',
                'description' => 'Enfocado en resolver el dolor de cabeza de compras: llevamos percheros con tallas XS a 3XL directamente a la clínica para prueba en vivo sin costo.',
                'subject' => '¿Problemas con las tallas de uniformes? Llevamos percheros de prueba directo a su clínica',
                'preheader' => 'Evite devoluciones y meses de espera. Servicio de tallaje presencial en terreno sin costo adicional para su institución.',
                'hero_title' => 'Servicio Exclusivo de Tallaje en su Propia Clínica',
                'hero_desc' => 'Sabemos que comprar uniformes para decenas de doctores y enfermeras suele terminar en tallas erróneas. En Suitable llevamos percheros móviles con curva completa (XS a 3XL) directo a sus instalaciones para que cada profesional se pruebe su talla antes de confeccionar.',
                'hero_image' => 'servicio-tallaje-terreno.jpg',
                'pilar1_title' => '1. Coordinamos la Visita',
                'pilar1_desc' => 'Agendamos fecha y hora que no interrumpa las rondas médicas de su clínica.',
                'pilar2_title' => '2. Percheros con Curva Completa',
                'pilar2_desc' => 'Llevamos muestras reales en todas las tallas para que el personal se pruebe en persona.',
                'pilar3_title' => '3. Entrega Exacta y Garantizada',
                'pilar3_desc' => 'Confección a medida con nombres bordados, 0% margen de error y 6 meses de garantía.',
                'cta_text' => 'Agendar Visita de Tallaje Gratuita →',
                'cta_url' => 'https://suitable.cl/agendar-tallaje',
                'layout_type' => 'process'
            ],
            [
                'id' => 'split',
                'name' => 'Split 50/50 Moderno',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '⚖️ Alta Lectura',
                'color' => '#146161',
                'icon' => '⚖️',
                'description' => 'Diseño minimalista estilo Apple/Brevo: Fotografía de alta costura clínica a la izquierda y propuesta ejecutiva con viñetas persuasivas a la derecha.',
                'subject' => 'Eleve el estándar visual de su institución: Confección clínica premium Suitable',
                'preheader' => 'Respaldo de fábrica, telas antifluidos Flex y calce ergonómico pensado para jornadas extenuantes.',
                'hero_title' => 'La Nueva Generación de Uniformes Médicos',
                'hero_desc' => 'Uniformes que combinan estética ejecutiva, protección biológica y flexibilidad física para instituciones médicas que buscan proyectar excelencia en cada detalle.',
                'hero_image' => 'tela-antifluidos-macro.jpg',
                'pilar1_title' => 'Confort Ergonómico Flex',
                'pilar1_desc' => 'Movilidad total en procedimientos quirúrgicos y turnos de urgencia sin deformar la prenda.',
                'pilar2_title' => 'Bioseguridad Comprobada',
                'pilar2_desc' => 'Barrera protectora certificada contra fluidos corporales y salpicaduras químicas.',
                'pilar3_title' => 'Respaldo Directo de Fábrica',
                'pilar3_desc' => 'Atención ejecutiva dedicada para reposiciones inmediatas y convenios anuales.',
                'cta_text' => 'Conocer Propuesta Corporativa →',
                'cta_url' => 'https://suitable.cl/contacto',
                'layout_type' => 'split'
            ],
            [
                'id' => 'showcase',
                'name' => 'Showcase 2x2 Cuadrícula',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '🖼️ Visual',
                'color' => '#0284C7',
                'icon' => '🖼️',
                'description' => 'Cuadrícula con 4 modelos y líneas de uniformes: Médico Quirúrgico, Enfermería & UCI, Odontología e Imagen Institucional.',
                'subject' => 'Catálogo Visual 2026: Descubra las 4 líneas clínicas de Suitable para su clínica',
                'preheader' => 'Desde scrubs quirúrgicos antibacteriales hasta batas ejecutivas de alta distinción.',
                'hero_title' => 'Uniformes Diseñados para Cada Área de su Clínica',
                'hero_desc' => 'Homogeneice la imagen de sus distintas unidades clínicas con uniformes acordes a la exigencia de cada especialidad.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Línea Quirúrgica Pro',
                'pilar1_desc' => 'Antifluido severo, respirabilidad máxima y costuras reforzadas.',
                'pilar2_title' => 'Línea Staff & Enfermería',
                'pilar2_desc' => 'Bolsillos funcionales multifuncionales y calce ultra cómodo.',
                'pilar3_title' => 'Línea Dental & Especialidades',
                'pilar3_desc' => 'Resistencia a tintes y lavados frecuentes a alta temperatura.',
                'cta_text' => 'Descargar Catálogo Completo 2026 →',
                'cta_url' => 'https://suitable.cl/catalogo-2026',
                'layout_type' => 'showcase'
            ],
            [
                'id' => 'dental_special',
                'name' => 'Convenio Clínicas Dentales',
                'category' => 'Especialidades',
                'category_slug' => 'especialidades',
                'badge' => '🦷 Odontología',
                'color' => '#0891B2',
                'icon' => '🦷',
                'description' => 'Enfocado en box dental: resistencia a hipoclorito/desinfectantes, movilidad para odontólogos sentados y bordado de especialidad.',
                'subject' => 'Scrubs clínicos que resisten desinfectantes y entregan movilidad total en box dental',
                'preheader' => 'Convenio especial para clínicas odontológicas: uniformes ergonómicos que mantienen color y forma tras cientos de lavados.',
                'hero_title' => 'Ergonomía y Protección Superior para su Equipo Odontológico',
                'hero_desc' => 'El trabajo dental exige postura sentada constante y protección ante aerosoles y salpicaduras. Los uniformes Suitable están confeccionados en tela Flex con tratamiento antibacterial y resistencia comprobada.',
                'hero_image' => 'tela-antifluidos-macro.jpg',
                'pilar1_title' => 'Resistencia a Manchas y Químicos',
                'pilar1_desc' => 'Telas que no se decoloran ni desgastan con desinfectantes de uso odontológico.',
                'pilar2_title' => 'Elasticidad Lumbar y Dorsal',
                'pilar2_desc' => 'Corte diseñado para libertad de movimiento en maniobras clínicas prolongadas.',
                'pilar3_title' => 'Bordado de Especialidades',
                'pilar3_desc' => 'Personalice con el logo de su clínica dental y la especialidad de cada doctor/a.',
                'cta_text' => 'Cotizar Convenio Dental →',
                'cta_url' => 'https://suitable.cl/convenio-dental',
                'layout_type' => 'split'
            ],
            [
                'id' => 'fabrica_directa',
                'name' => 'Directo de Fábrica (Ahorro 30%)',
                'category' => 'Ejecutivo & Finanzas',
                'category_slug' => 'finanzas',
                'badge' => '🏭 Ahorro B2B',
                'color' => '#16A34A',
                'icon' => '🏭',
                'description' => 'Argumento financiero sólido para directores de adquisiciones: comprar directo al fabricante nacional sin márgenes de distribuidores.',
                'subject' => 'Optimice el presupuesto de uniformes de su clínica: Ahorre hasta un 30% directo de fábrica',
                'preheader' => 'Sin intermediarios ni sobreprecios. Cotice directo con el fabricante chileno con respaldo y stock garantizado.',
                'hero_title' => 'Compre Directo de Fábrica y Optimice su Presupuesto B2B',
                'hero_desc' => 'Al comprar con Suitable, usted trata directamente con los fabricantes. Eliminamos la cadena de revendedores para ofrecer precios mayoristas transparentes, trazabilidad en la producción y garantía real de 6 meses.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Precios de Fábrica Sin Recargo',
                'pilar1_desc' => 'Acceda a tarifas preferenciales por volumen con facturación directa y crédito comercial.',
                'pilar2_title' => 'Tiempos de Entrega Récord',
                'pilar2_desc' => 'Talleres en Chile que responden en días, no en los meses que tarda una importación.',
                'pilar3_title' => 'Garantía 6 Meses Sin Letra Chica',
                'pilar3_desc' => 'Si alguna costura falla, respondemos de inmediato con reposición directa.',
                'cta_text' => 'Solicitar Cuadro de Ahorro Mayorista →',
                'cta_url' => 'https://suitable.cl/cotizar-mayorista',
                'layout_type' => 'pillars'
            ],
            [
                'id' => 'antifluido_tech',
                'name' => 'Tecnología Antifluido Certificada',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '🛡️ Bioseguridad',
                'color' => '#2563EB',
                'icon' => '🛡️',
                'description' => 'Demostración visual y técnica del tejido hidrofóbico: las gotas de agua y fluidos resbalan sin penetrar la fibra textil.',
                'subject' => 'Bioseguridad en quirófano: conozca la tela antifluido con certificación que protege a su personal',
                'preheader' => 'Barrera líquida impenetrable con tecnología transpirable. Solicite muestra física en su oficina.',
                'hero_title' => 'Máxima Protección Líquida con Tecnología Flex 4-Way',
                'hero_desc' => 'La bioseguridad del personal médico es prioritaria. Nuestras telas antifluidos forman una barrera hidrofóbica molecular que hace que la sangre, fluidos y soluciones resbalen instantáneamente sin manchar la prenda.',
                'hero_image' => 'tela-antifluidos-macro.jpg',
                'pilar1_title' => 'Repelencia de Fluidos Nivel Hospitalario',
                'pilar1_desc' => 'Evita el traspaso de líquidos protegiendo la piel del profesional de la salud.',
                'pilar2_title' => 'Transpirabilidad Termorreguladora',
                'pilar2_desc' => 'Tejido microperforado transpirable que evita la sudoración excesiva bajo luces de pabellón.',
                'pilar3_title' => 'Durabilidad de 100+ Lavados',
                'pilar3_desc' => 'El tratamiento antifluido permanece activo incluso tras rigurosos lavados industriales.',
                'cta_text' => 'Solicitar Muestra de Tela Gratis →',
                'cta_url' => 'https://suitable.cl/muestra-textil',
                'layout_type' => 'split'
            ],
            [
                'id' => 'licitaciones',
                'name' => 'Licitaciones & Hospitales Públicos',
                'category' => 'Ejecutivo & Finanzas',
                'category_slug' => 'finanzas',
                'badge' => '📋 Mercado Público',
                'color' => '#475569',
                'icon' => '📋',
                'description' => 'Redacción sobria y técnica diseñada para comisiones de compras públicas, convenios marco y jefaturas de abastecimiento.',
                'subject' => 'Ficha Técnica y Catálogo de Uniformes Clínicos para Comités de Adquisiciones',
                'preheader' => 'Proveedor registrado. Cumplimiento estricto de bases técnicas, garantía de 6 meses y despacho garantizado a nivel nacional.',
                'hero_title' => 'Respaldo Institucional para Adquisiciones Hospitalarias',
                'hero_desc' => 'Suitable cumple con los más altos estándares técnicos exigidos por el sector salud en Chile: trazabilidad de origen, certificaciones textiles, capacidad productiva a gran escala y cumplimiento riguroso de plazos.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Fichas Técnicas Certificadas',
                'pilar1_desc' => 'Detalle de composición, gramaje textil, solidez al frote y resistencia a la tracción.',
                'pilar2_title' => 'Capacidad Productiva Masiva',
                'pilar2_desc' => 'Capacidad para abastecer dotaciones de 100 a más de 2.000 profesionales sin quiebres de stock.',
                'pilar3_title' => 'Garantía y Seriedad Comercial',
                'pilar3_desc' => 'Documentación legal al día, facturación electrónica y atención por ejecutivos senior.',
                'cta_text' => 'Descargar Ficha Técnica y Bases →',
                'cta_url' => 'https://suitable.cl/ficha-tecnica',
                'layout_type' => 'pillars'
            ],
            [
                'id' => 'estetica_premium',
                'name' => 'Estética & Dermocosmética VIP',
                'category' => 'Especialidades',
                'category_slug' => 'especialidades',
                'badge' => '✨ Estética & Spa',
                'color' => '#BE185D',
                'icon' => '✨',
                'description' => 'Estilo sofisticado y minimalista pensado para clínicas dermatológicas, centros estéticos y cirujanos plásticos.',
                'subject' => 'Elegancia y distinción para su centro médico estético: Uniformes clínicos de alta costura',
                'preheader' => 'Proyecte exclusividad desde la primera consulta. Diseños entallados, colores de tendencia y telas de tacto sedoso.',
                'hero_title' => 'La Imagen Sofisticada que sus Pacientes Esperan',
                'hero_desc' => 'En el rubro de la medicina estética, la imagen visual lo es todo. Nuestros uniformes combinan cortes entallados de alta costura con telas premium antifluidos en colores de tendencia (azul petróleo, palo rosa, grafito y perla).',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Cortes Silueta Ejecutiva',
                'pilar1_desc' => 'Diseño refinado que estiliza la figura sin sacrificar la movilidad profesional.',
                'pilar2_title' => 'Tacto Ultrasuave Sedoso',
                'pilar2_desc' => 'Telas con caída impecable que no se arrugan durante la jornada de consultas.',
                'pilar3_title' => 'Colores Exclusivos',
                'pilar3_desc' => 'Paleta tonal refinada acorde a la identidad corporativa de su centro estético.',
                'cta_text' => 'Ver Colección Estética 2026 →',
                'cta_url' => 'https://suitable.cl/coleccion-estetica',
                'layout_type' => 'split'
            ],
            [
                'id' => 'descuento_volumen',
                'name' => 'Descuento Mayorista por Volumen',
                'category' => 'Ofertas & Volumen',
                'category_slug' => 'ofertas',
                'badge' => '⚡ Escala B2B',
                'color' => '#DC2626',
                'icon' => '⚡',
                'description' => 'Escala de descuentos por cantidad (15%, 25%, 35%) con llamado de urgencia para compras de dotación institucional.',
                'subject' => 'Tarifas preferenciales por volumen: Hasta 35% de descuento en dotaciones médicas 2026',
                'preheader' => 'Válido para compras sobre 20 conjuntos clínicos. Confección chilena con bordado de regalo.',
                'hero_title' => 'Maximice el Rendimiento de su Compra Corporativa',
                'hero_desc' => 'Abra un convenio mayorista con Suitable y acceda a nuestra escala de precios por dotación institucional. Mientras mayor sea el equipo a vestir, mayor será el ahorro por prenda, incluyendo bordado computarizado sin costo.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Desde 20 Unidades: 15% OFF',
                'pilar1_desc' => 'Ideal para clínicas pequeñas y consultas especializadas.',
                'pilar2_title' => 'Desde 50 Unidades: 25% OFF',
                'pilar2_desc' => 'Incluye servicio de tallaje en terreno gratuito y prueba de prendas.',
                'pilar3_title' => 'Desde 100+ Unidades: 35% OFF',
                'pilar3_desc' => 'Tarifa de contrato marco anual con bordado de logo institucional sin costo.',
                'cta_text' => 'Calcular Ahorro de mi Clínica →',
                'cta_url' => 'https://suitable.cl/calculadora-descuentos',
                'layout_type' => 'process'
            ],
            [
                'id' => 'laboratorios',
                'name' => 'Laboratorios Clínicos & Toma de Muestra',
                'category' => 'Especialidades',
                'category_slug' => 'especialidades',
                'badge' => '🔬 Laboratorios',
                'color' => '#0D9488',
                'icon' => '🔬',
                'description' => 'Enfoque en alta higiene, resistencia a reactivos químicos, facilidad de lavado enérgico y bolsillos especializados.',
                'subject' => 'Uniformes resistentes a reactivos y lavados clínicos para personal de laboratorio',
                'preheader' => 'Protección y durabilidad textil garantizada para tecnólogos médicos y flebotomistas.',
                'hero_title' => 'Protección Rigurosa para Análisis y Toma de Muestras',
                'hero_desc' => 'El personal de laboratorio enfrenta diariamente agentes químicos y biológicos. Nuestras prendas proporcionan un escudo protector eficaz con costuras selladas y telas tratadas contra la adherencia bacteriana.',
                'hero_image' => 'tela-antifluidos-macro.jpg',
                'pilar1_title' => 'Barrera Química Liviana',
                'pilar1_desc' => 'Tejido que repele reactivos habituales y soluciones salinas.',
                'pilar2_title' => 'Bolsillos Porta-Instrumentos',
                'pilar2_desc' => 'Diseño funcional con compartimentos específicos para tubos, tijeras y credenciales.',
                'pilar3_title' => 'Lavado de Alta Higiene',
                'pilar3_desc' => 'Aptos para ciclos de lavado térmico institucional sin perder sus propiedades repelentes.',
                'cta_text' => 'Solicitar Propuesta para Laboratorios →',
                'cta_url' => 'https://suitable.cl/laboratorios',
                'layout_type' => 'split'
            ],
            [
                'id' => 'black_scrub',
                'name' => 'Colección Black & Petróleo VIP',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '👔 Edición Especial',
                'color' => '#0F172A',
                'icon' => '👔',
                'description' => 'Uniformes sobrios y elegantes en negro grafito y azul petróleo profundo para médicos tratantes y jefaturas.',
                'subject' => 'Nueva Colección Black & Azul Petróleo: Distinción para el cuerpo médico de su clínica',
                'preheader' => 'Tonalidades sobrias que inspiran confianza y autoridad médica. Confección en tela Flex 4-Way.',
                'hero_title' => 'Autoridad, Sobriedad y Alta Distinción Médica',
                'hero_desc' => 'La nueva paleta de tonalidades oscuras de Suitable está diseñada para médicos tratantes, cirujanos y jefes de servicio que buscan una imagen de serenidad, autoridad profesional y diseño impecable.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Fijación de Color Intensa',
                'pilar1_desc' => 'Tintura reactiva que no pierde su intensidad tras múltiples lavados hospitalarios.',
                'pilar2_title' => 'Detalles en Costuras Reforzadas',
                'pilar2_desc' => 'Puntadas de alta resistencia con terminaciones finas en cuellos y bolsillos.',
                'pilar3_title' => 'Bordado Institucional en Plata',
                'pilar3_desc' => 'Contraste perfecto para logotipos clínicos bordados con hilo satinado.',
                'cta_text' => 'Conocer Edición Ejecutiva →',
                'cta_url' => 'https://suitable.cl/coleccion-black',
                'layout_type' => 'showcase'
            ],
            [
                'id' => 'renovacion_staff',
                'name' => 'Renovación Periódica de Dotación',
                'category' => 'Ofertas & Volumen',
                'category_slug' => 'ofertas',
                'badge' => '🔄 Reposición Fácil',
                'color' => '#EAB308',
                'icon' => '🔄',
                'description' => 'Plan de reposición programada para clínicas con recambio semestral de uniformes o incorporaciones de personal.',
                'subject' => '¿Hora de renovar la dotación de uniformes de su clínica? Plan de recambio ágil Suitable',
                'preheader' => 'Mantenemos el historial de tallas y logos de su equipo para que pedir reposiciones tome menos de 5 minutos.',
                'hero_title' => 'Renueve la Dotación Médica de su Clínica sin Complicaciones',
                'hero_desc' => 'En Suitable guardamos las fichas de tallaje y las especificaciones exactas de su clínica. Cuando ingresa nuevo personal o llega la fecha de recambio anual, simplemente nos indica la cantidad y producimos de inmediato sin trámites tediosos.',
                'hero_image' => 'servicio-tallaje-terreno.jpg',
                'pilar1_title' => 'Ficha de Cliente Guardada',
                'pilar1_desc' => 'Registramos las tallas, colores y logos exactos de su institución para pedidos instantáneos.',
                'pilar2_title' => 'Despacho Programado',
                'pilar2_desc' => 'Entregas parcializadas según la fecha de ingreso de sus nuevos colaboradores.',
                'pilar3_title' => 'Congelamiento de Tarifas',
                'pilar3_desc' => 'Garantizamos precios estables durante todo el año mediante convenio marco.',
                'cta_text' => 'Revisar Plan de Reposición Anual →',
                'cta_url' => 'https://suitable.cl/plan-recambio',
                'layout_type' => 'pillars'
            ],
            [
                'id' => 'pediatria_confort',
                'name' => 'Pediatría & Maternidad Confort',
                'category' => 'Especialidades',
                'category_slug' => 'especialidades',
                'badge' => '🧸 Amabilidad',
                'color' => '#8B5CF6',
                'icon' => '🧸',
                'description' => 'Colores amables, máxima suavidad al tacto y flexibilidad pensados para el trato con niños, recién nacidos y madres.',
                'subject' => 'Uniformes clínicos suaves y reconfortantes para sus unidades de pediatría y maternidad',
                'preheader' => 'Colores cálidos que reducen el estrés en niños, con la máxima bioseguridad para el personal.',
                'hero_title' => 'Calidez Humana y Movilidad Total en Pediatría',
                'hero_desc' => 'La atención pediátrica requiere empatía visual y prendas suaves al tacto de los más pequeños. Nuestra línea materno-infantil combina tonos reconfortantes con tela elástica ultraliviana que permite agacharse y moverse con total naturalidad.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Colores Cálidos y Amigables',
                'pilar1_desc' => 'Verde menta, celeste cielo y lavanda suave que transmiten calma a los pacientes infantiles.',
                'pilar2_title' => 'Tacto Hipoalergénico Sedoso',
                'pilar2_desc' => 'Fibras suaves libres de asperezas, ideales para el contacto con la piel sensible de lactantes.',
                'pilar3_title' => 'Movilidad Multidireccional',
                'pilar3_desc' => 'Flexibilidad total para atender en cunas, camillas y áreas de juego clínico.',
                'cta_text' => 'Ver Línea Pediátrica Suitable →',
                'cta_url' => 'https://suitable.cl/pediatria',
                'layout_type' => 'split'
            ],
            [
                'id' => 'entrega_express',
                'name' => 'Entrega Express (Stock Disponible)',
                'category' => 'Ofertas & Volumen',
                'category_slug' => 'ofertas',
                'badge' => '⏱️ Envíos Rápidos',
                'color' => '#F97316',
                'icon' => '⏱️',
                'description' => 'Para instituciones que abren nuevas sucursales o tienen contrataciones urgentes y no pueden esperar 6 semanas.',
                'subject' => '¿Necesita uniformes clínicos de urgencia? Despacho en 48/72 horas con stock listo',
                'preheader' => 'Conjuntos médicos completos en colores corporativos con bordado express disponible.',
                'hero_title' => 'Solución Inmediata para Nuevas Contrataciones y Urgencias',
                'hero_desc' => 'Si su clínica está incorporando personal urgente o inaugurando una nueva sede, en Suitable contamos con stock permanente de nuestras tallas más demandadas para despacho prioritario en tiempo récord.',
                'hero_image' => 'servicio-tallaje-terreno.jpg',
                'pilar1_title' => 'Despacho Inmediato',
                'pilar1_desc' => 'Envíos en 48 a 72 horas para conjuntos en stock a cualquier región de Chile.',
                'pilar2_title' => 'Bordado Express Computarizado',
                'pilar2_desc' => 'Personalizamos con el logo de su clínica en tiempo récord en nuestros propios talleres.',
                'pilar3_title' => 'Sin Pedido Mínimo Excesivo',
                'pilar3_desc' => 'Atendemos desde 5 unidades para completar su dotación médica urgente.',
                'cta_text' => 'Consultar Stock Disponible Ahora →',
                'cta_url' => 'https://suitable.cl/stock-express',
                'layout_type' => 'process'
            ],
            [
                'id' => 'bordados_corporativos',
                'name' => 'Bordados Computarizados de Alta Definición',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '🧵 Identidad de Marca',
                'color' => '#059669',
                'icon' => '🧵',
                'description' => 'Destaca la personalización con el logotipo institucional bordado con hilos alemanes de alta fidelidad cromática.',
                'subject' => 'Proyecte la identidad de su clínica con bordados computarizados de alta precisión',
                'preheader' => 'Hilos de alta fidelidad que no destiñen ni se deshilachan con el lavado hospitalario.',
                'hero_title' => 'La Identidad de su Institución en Cada Prenda',
                'hero_desc' => 'Un bordado de calidad transforma una prenda común en un emblema institucional. En Suitable contamos con matricería digital propia e hilos de alta resistencia para plasmar su isotipo y los nombres de sus especialistas con nitidez absoluta.',
                'hero_image' => 'tela-antifluidos-macro.jpg',
                'pilar1_title' => 'Matricería Digital Exacta',
                'pilar1_desc' => 'Digitalización precisa de sus colores Pantone y tipografía corporativa.',
                'pilar2_title' => 'Hilos Alemanes Indestructibles',
                'pilar2_desc' => 'Resistencia absoluta a detergentes hospitalarios, autoclave y planchado.',
                'pilar3_title' => 'Bordado Personalizado por Profesional',
                'pilar3_desc' => 'Nombre, apellido y especialidad médica bordados con perfecta legibilidad.',
                'cta_text' => 'Solicitar Muestra Digital de su Logo →',
                'cta_url' => 'https://suitable.cl/bordados',
                'layout_type' => 'split'
            ],
            [
                'id' => 'roi_compras',
                'name' => 'Estudio de Durabilidad & ROI para Finanzas',
                'category' => 'Ejecutivo & Finanzas',
                'category_slug' => 'finanzas',
                'badge' => '📊 Rentabilidad',
                'color' => '#047857',
                'icon' => '📊',
                'description' => 'Análisis comparativo de costo por uso: un uniforme Suitable dura 3 veces más que un scrub desechable importado.',
                'subject' => 'Costo por postura: Cómo Suitable reduce en un 40% el gasto anual en vestuario clínico',
                'preheader' => '6 meses de garantía real vs prendas que pierden color al tercer mes. Compare cifras con nuestro cuadro B2B.',
                'hero_title' => 'Menor Costo por Uso: La Decisión Inteligente para Finanzas',
                'hero_desc' => 'Comprar uniformes baratos suele ser el camino más caro: telas que se rompen, costuras que ceden y quejas constantes del personal. Suitable ofrece 6 meses de garantía de fábrica porque nuestras prendas están confeccionadas para durar años.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => '3x Mayor Vida Útil Textil',
                'pilar1_desc' => 'Gramaje y densidad hilada que soportan el desgaste de turnos dobles continuos.',
                'pilar2_title' => 'Cero Costo de Reemplazos Prematuros',
                'pilar2_desc' => 'Garantía directa de 6 meses: si algo falla en costuras o tela, lo cambiamos sin costo.',
                'pilar3_title' => 'Mayor Satisfacción del Personal',
                'pilar3_desc' => 'Personal médico cómodo y motivado, reflejando el estándar de cuidado de su clínica.',
                'cta_text' => 'Descargar Estudio Comparativo de Costos →',
                'cta_url' => 'https://suitable.cl/comparativa-roi',
                'layout_type' => 'pillars'
            ],
            [
                'id' => 'alianza_redes',
                'name' => 'Convenio Red de Clínicas & Centros Médicos',
                'category' => 'Ejecutivo & Finanzas',
                'category_slug' => 'finanzas',
                'badge' => '🤝 Contrato Marco',
                'color' => '#1D4ED8',
                'icon' => '🤝',
                'description' => 'Acuerdo marco corporativo para redes con múltiples sucursales: precios fijos, despacho nacional y portal de pedidos.',
                'subject' => 'Convenio Marco para Redes Clínicas: Precios fijos y despacho a todas sus sedes',
                'preheader' => 'Un solo proveedor nacional para todas sus sucursales. Facturación centralizada y atención ejecutiva.',
                'hero_title' => 'Un Solo Estándar de Vestuario para Todas sus Sucursales',
                'hero_desc' => 'Homogeneice la vestimenta clínica de toda su red en Santiago y regiones. Mediante nuestro Convenio Marco, su institución accede a una lista de precios congelada, ejecutiva de cuenta preferente y logística de entrega en cada centro.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => 'Tarifas Congeladas por 12 Meses',
                'pilar1_desc' => 'Presupueste su gasto anual sin sorpresas por variaciones de tipo de cambio.',
                'pilar2_title' => 'Logística a Nivel Nacional',
                'pilar2_desc' => 'Despachamos directamente a cada una de sus sedes con rotulado por unidad.',
                'pilar3_title' => 'Facturación y Crédito B2B',
                'pilar3_desc' => 'Condiciones de pago a 30 y 60 días para instituciones asociadas.',
                'cta_text' => 'Solicitar Reunión para Convenio Marco →',
                'cta_url' => 'https://suitable.cl/convenio-marco',
                'layout_type' => 'split'
            ],
            [
                'id' => 'social_proof',
                'name' => 'Casos de Éxito & Testimonios Clínicos',
                'category' => 'B2B & Clínicas',
                'category_slug' => 'clinicas',
                'badge' => '🌟 Confianza',
                'color' => '#7C3AED',
                'icon' => '🌟',
                'description' => 'Prueba social con testimonios de directores de enfermería y encargados de adquisiciones que ya visten Suitable.',
                'subject' => 'Por qué más de 50 clínicas en Chile ya confían en Suitable para vestir a su personal',
                'preheader' => 'Conozca la experiencia de directores médicos que cambiaron los uniformes importados por confección chilena.',
                'hero_title' => 'Más de 50 Instituciones Médicas en Chile Visten con Suitable',
                'hero_desc' => 'Equipos de urgencia, clínicas odontológicas y centros de diagnóstico de primer nivel en Chile han transformado la comodidad de su personal y la imagen de su institución con nuestros uniformes.',
                'hero_image' => 'hero-grupo-clinico.jpg',
                'pilar1_title' => '98.5% de Satisfacción del Personal',
                'pilar1_desc' => 'Evaluación sobresaliente en comodidad, frescura de tela y ajuste anatómico.',
                'pilar2_title' => 'Cero Devoluciones por Talla',
                'pilar2_desc' => 'Gracias a nuestro sistema de tallaje presencial en vivo en cada institución.',
                'pilar3_title' => 'Respaldado por Garantía Local',
                'pilar3_desc' => 'La tranquilidad de tratar con una fábrica ubicada en Chile con respuesta inmediata.',
                'cta_text' => 'Leer Casos de Éxito Clínico →',
                'cta_url' => 'https://suitable.cl/casos-exito',
                'layout_type' => 'pillars'
            ],
            [
                'id' => 'muestrario_caja',
                'name' => 'Caja de Muestras Físicas Sin Costo',
                'category' => 'Tallaje & Servicio',
                'category_slug' => 'tallaje',
                'badge' => '🎁 Muestras Gratis',
                'color' => '#10B981',
                'icon' => '🎁',
                'description' => 'Oferta de bajo compromiso: enviamos una caja con retazos de telas, muestras de bordados y un scrub real a su oficina.',
                'subject' => 'Enviamos una Caja de Muestras y Telas Suitable a su oficina sin costo alguno',
                'preheader' => 'Toque la calidad de la tela Flex antifluidos y compruebe la confección antes de tomar cualquier decisión.',
                'hero_title' => 'Compruebe la Calidad Textil con sus Propias Manos',
                'hero_desc' => 'Las fotos no siempre transmiten la verdadera suavidad y elasticidad de una tela. Por eso, enviamos gratuitamente a la oficina de su comité de compras un kit físico con muestras de telas antifluido, ejemplos de bordados y un conjunto de muestra.',
                'hero_image' => 'tela-antifluidos-macro.jpg',
                'pilar1_title' => 'Muestras de Telas Flex Antifluido',
                'pilar1_desc' => 'Compruebe usted mismo vertiendo agua: las gotas resbalan sin humedecer la tela.',
                'pilar2_title' => 'Paleta Cromática Real en Vivo',
                'pilar2_desc' => 'Vea los colores exactos bajo la iluminación de su clínica antes de encargar.',
                'pilar3_title' => '100% Gratuito y Sin Compromiso',
                'pilar3_desc' => 'Envío sin costo por courier directo a su clínica o centro de atención médica.',
                'cta_text' => 'Pedir mi Caja de Muestras Gratis →',
                'cta_url' => 'https://suitable.cl/pedir-muestrario',
                'layout_type' => 'split'
            ]
        ];
    }

    /**
     * Find a preset by its ID
     */
    public static function find(string $id): ?array
    {
        $all = self::all();
        foreach ($all as $preset) {
            if ($preset['id'] === $id) {
                return $preset;
            }
        }
        return $all[0] ?? null;
    }

    /**
     * Get unique categories
     */
    public static function categories(): array
    {
        return [
            ['slug' => 'all', 'name' => 'Todos los Presets', 'count' => 20, 'icon' => '📑'],
            ['slug' => 'clinicas', 'name' => 'B2B & Clínicas', 'count' => 6, 'icon' => '🏥'],
            ['slug' => 'tallaje', 'name' => 'Tallaje & Servicio', 'count' => 3, 'icon' => '📏'],
            ['slug' => 'especialidades', 'name' => 'Especialidades Médicas', 'count' => 4, 'icon' => '🦷'],
            ['slug' => 'ofertas', 'name' => 'Ofertas & Volumen', 'count' => 4, 'icon' => '⚡'],
            ['slug' => 'finanzas', 'name' => 'Ejecutivo & Finanzas', 'count' => 3, 'icon' => '📊'],
        ];
    }
}
